config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :audios
  resources :images
  # resources :post_contents
  resources :posts do
    resources :post_contents, controller: 'post_contents'

    member do
      get :toggle
    end
  end
  resources :labels
  resources :menus
  resources :local_names
  resources :country_names
  resources :countries
  resources :locals
  resources :languages
  devise_for :users
  namespace :api do
    resources :locals do
      collection do
        get :home 
      end
    end
    resources :languages
    resources :countries
    resources :labels
    resources :favorites
    resources :itineraries 
    resources :posts do
      collection do
        get :get_itineraries
        get :get_lat_lng
      end
    end

    post '/login' => 'sessions#signin'
    
    get '/auth' => 'users#get_user'
    post '/sign_up' => 'users#create'
    put '/users' => 'users#update_user'
    delete 'users/:id' => 'users#destroy'
    
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/language.rb
class Language < ApplicationRecord
  validates :name, presence: true

  has_many :country_names, dependent: :destroy
  has_many :local_names, dependent: :destroy
  has_many :labels, dependent: :destroy
  has_many :menus, dependent: :destroy
  has_many :post_contents, dependent: :destroy

  after_create :create_locals
  after_create :create_countries
  after_create :create_post
  after_create :create_labels


  def create_locals
    Local.all.each do |local|
      LocalName.create(name: local.name, language_id: self.id, local_id: local.id)
    end
  end
  
  def create_countries
    Country.all.each do |country|
      CountryName.create(name: country.name, language_id: self.id, country_id: country.id)
    end
  end

  def create_post
    Post.all.each do |post|
      PostContent.create!(title: post.title, subtitle: post.subtitle, content: post.content, language_id: self.id, post_id: post.id)
    end
  end

  def create_labels
    Label.create( my_favorites: "My Favorites", already_visited: "Already Visited", my_itinerary: "My Itinerary", remove_all: "Remove All", add: "Add", save_button: "Save", view_in_map: "View In Map", share: "Share", reorder: "reorder", edit: "Edit", delete_button: "Delete", choose_itinerary_name: "Choose Itinerary Name", language_id: self.id)
  end

  # def create_menus_and_labels
  #   language_id = Language.first.id
  #   @labels = Label.where(language_id: language_id)
  #   @menus = Menu.where(language_id: language_id)
  #   @buttons = Button.where(language_id: language_id)

  #   @labels.each do |label|
  #     new_label = label.dup
  #     new_label.language_id = self.id
  #     new_label.save!
  #   end
    
  #   @menus.each do |menu|
  #     new_menu = menu.dup
  #     new_menu.language_id = self.id
  #     new_menu.save!
  #   end
    
  #   @buttons.each do |button|
  #     new_button = button.dup
  #     new_button.language_id = self.id
  #     new_button.save!
  #   end
  # end
end

app/controllers/api/languages_controller.rb
class Api::LanguagesController < ApiController
  skip_before_action :authenticate_request
  def index
    @languages = Language.all

    render json: @languages
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: %i[ show edit update destroy ]

  # GET /languages or /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/1 or /languages/1.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages or /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to languages_url, notice: "Language was successfully created." }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1 or /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to languages_url, notice: "Language was successfully updated." }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1 or /languages/1.json
  def destroy
    @language.destroy

    respond_to do |format|
      format.html { redirect_to languages_url, notice: "Language was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def language_params
      params.require(:language).permit(:name)
    end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.erb
<%= simple_form_for(@language) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, input_html: { class: "form-control" } %>
  </div>
    
  <div class="form-actions mt-4">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/languages/_language.html.erb
<tr>
  <td><%= language.name %></td>
  <td>
    <%= link_to "Edit", edit_language_path(language), class: "btn btn-success" %>
    <%= link_to "Remove", language_path(language), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger" %>
  </td>
</tr>

app/views/languages/edit.html.erb
<%- model_class = Language -%>
<div class="flex-row d-flex justify-content-between align-items-center p-4">
  <h3 class="fs-4">Edit Language</h3>
  <%= link_to "Back", languages_path, class: "btn btn-primary w-auto" %>
</div>

<%= render "form", language: @language %>

app/views/languages/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="row">
  <div class="col">
    <h1 class="mt-4">Languages</h1>
  </div>
  <div class="col d-flex justify-content-end align-items-center">
    <%= link_to "New Language", new_language_path, class: "btn btn-primary w-auto" %>
  </div>
</div>
<div class="row">
  <table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
      <% @languages.each do |language| %>
        <%= render language %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/languages/new.html.erb
<%- model_class = Language -%>
<div class="flex-row d-flex justify-content-between align-items-center p-4">
  <h3 class="fs-4">New Language</h3>
  <%= link_to "Back", languages_path, class: "btn btn-primary w-auto" %>
</div>

<%= render "form", language: @language %>

app/views/languages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @language %>

<div>
  <%= link_to "Edit this language", edit_language_path(@language) %> |
  <%= link_to "Back to languages", languages_path %>

  <%= button_to "Destroy this language", @language, method: :delete %>
</div>