config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :audios
  resources :images
  # resources :post_contents
  resources :posts do
    resources :post_contents, controller: 'post_contents'

    member do
      get :toggle
    end
  end
  resources :labels
  resources :menus
  resources :local_names
  resources :country_names
  resources :countries
  resources :locals
  resources :languages
  devise_for :users
  namespace :api do
    resources :locals do
      collection do
        get :home 
      end
    end
    resources :languages
    resources :countries
    resources :labels
    resources :favorites
    resources :itineraries 
    resources :posts do
      collection do
        get :get_itineraries
        get :get_lat_lng
      end
    end

    post '/login' => 'sessions#signin'
    
    get '/auth' => 'users#get_user'
    post '/sign_up' => 'users#create'
    put '/users' => 'users#update_user'
    delete 'users/:id' => 'users#destroy'
    
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :country
  belongs_to :local

  has_many :post_contents, dependent: :destroy
  has_many :audios, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :itineraries, dependent: :destroy

  # has_rich_text :content

  ## ACTIVE STORAGE
  has_one_attached :image


  accepts_nested_attributes_for :post_contents,
            reject_if: :all_blank,
            allow_destroy: true
  accepts_nested_attributes_for :audios,
            reject_if: :all_blank,
            allow_destroy: true
  accepts_nested_attributes_for :images,
            reject_if: :all_blank,
            allow_destroy: true


  after_create :create_post_contents_any_language

  def create_post_contents_any_language
    Language.all.each do |language|
      PostContent.create!(title: self.title, subtitle: self.subtitle, content: self.content, language_id: language.id, post_id: self.id)
    end
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApiController
  skip_before_action :authenticate_request
  def index
    @q = Post.ransack(params[:q])
    
    posts = @q.result.map do |post|
      post.post_contents.where(language_id: @language.id).last
    end

    render json: posts
  end

  def get_lat_lng
    posts = Post.where.not(lat: nil, lng: nil).map{|post| { name: post.title, lat_lng: [post.lat, post.lng] }}
    
    render json: posts
  end

  def get_itineraries
    @locals = Local.where.not(id: 1)

    locals =  @locals.map do |local|
      local.local_names.where(language_id: @language.id).last
    end

    @itineraries = locals.map do |local|
      @q = Post.where(local_id: local.local_id)
      
      posts = @q.map do |post|
        post.post_contents.where(language_id: @language.id).last
      end

      {
        local: local,
        posts: ActiveModelSerializers::SerializableResource.new(posts, each_serializer: PostContentSerializer)
      }
    end


    render json: @itineraries
  end

  def show
    @post = Post.find(params[:id])

    render json: @post.post_contents.where(language_id: @language.id).last
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy toggle]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :asc)
  end
  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.images.build
    @post.audios.build
  end

  # GET /posts/1/edit
  def edit
    @post.images.build unless @post.images.present?
    @post.audios.build unless @post.audios.present?
  end

  def toggle
    @post.update has_home: !@post.has_home

    redirect_to posts_path
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.local_id = @post.country&.local&.id
    respond_to do |format|
      if @post.save!
        format.html { redirect_to posts_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        @post.images.build unless @post.images.present?
        @post.audios.build unless @post.audios.present?
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        @post.images.build unless @post.images.present?
        @post.audios.build unless @post.audios.present?
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit!
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <h3>Main Image</h3>
    <%= f.input :image, input_html: { class: "form-control" } %>
    <hr />

    <div id='images'>
      <h3>Gallery Images</h3>
      <%= f.simple_fields_for :images do |image| %>
        <%= render 'image_fields', :f => image %>
      <% end %>
      <div class='links'>
        <%= link_to_add_association 'add image', f, :images, class: "btn btn-primary mt-4" %>
      </div>
    </div>
    <hr />
   
    <%= f.simple_fields_for :audios do |audio| %>
      <h3>Audio</h3>
      <%= audio.input :file, as: :file, input_html: { class: "form-control" } %>
    <% end %>

    <hr />
    <h3>General Data</h3>
    <%= f.input :lat, input_html: { class: "form-control" } %>
    <%= f.input :lng, input_html: { class: "form-control" } %>
    <%= f.association :country, label: "Sub-Category", label_method: :name_country, input_html: { class: "form-control" } %>
    <%#= f.association :local, input_html: { class: "form-control" } %>
    <hr />

    <% if @post.new_record? %>
      <h3>Content Post</h3>

      <%= f.input :title, input_html: { class: "form-control" } %>
      <%= f.input :subtitle, input_html: { class: "form-control" } %>
      <%##= f.input :content, as: :rich_text_area, input_html: { class: "form-control" }  %>
      <br />
      <%= f.cktext_area :content, id: 'sometext', input_html: {ckeditor: { toolbar: 'Full' }}  %>
      <br />
<%#= f.input :content, input_html: {class: 'form-control form-control-user ckeditor', ckeditor: { toolbar: 'Fll' }}, label: "Content" %>
       <%#= f.input :content, class: 'form-control form-control-user', label: "Content", as: :ckeditor %>
    <% end %>
  </div>

  <div class="form-actions mt-4">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_image_fields.html.erb
<div class="nested-fields row align-items-center">
  <div class="col-8">
    <%= f.input :file, as: :file, input_html: { class: "form-control" } %>
  </div>
  <div class="text-center align-middle col-4 mt-4">
    <%= link_to_remove_association f, class: 'btn btn-danger tippy', :'data-tippy-content' => 'Remove Image' do %>
      Remove
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Lat:</strong>
    <%= post.lat %>
  </p>

  <p>
    <strong>Lng:</strong>
    <%= post.lng %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= post.country_id %>
  </p>

  <p>
    <strong>Local:</strong>
    <%= post.local_id %>
  </p>

</div>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="flex-row d-flex justify-content-between align-items-center p-4">
  <h3 class="fs-4">Editar Postagem</h3>
  <%= link_to "Back", posts_path, class: "btn btn-primary w-auto" %>
</div>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="row">
  <div class="col">
    <h1 class="mt-4">Post</h1>
  </div>
  <div class="col d-flex justify-content-end align-items-center">
    <%= link_to "New Posts", new_post_path, class: "btn btn-primary w-auto" %>
  </div>
</div>
<div class="row">
  <% @posts.each do |post| %>
    <div class="col-xl-3 col-md-6">
        <div class="card" style="width: 18rem">
          <%= image_tag post.image.persisted? ? post.image : "default-image.jpg", class: "card-img-top", style: "height: 160px;" %>
          <div class="card-body">
            <h5 class="card-title"><%= post.title %></h5>
            <p class="card-text"><%= post.subtitle %></p>
          </div>
           <div class="card-body ">
            <%= link_to "Edit Post", edit_post_path(post.id), class: "small btn btn-success ", style: "font-size: 12px;margin: 8px;" %>
            <%= link_to "Edit Post Content", post_post_contents_path(post.id), class: "small btn btn-primary ", style: "font-size: 12px;margin: 8px;"  %>
            <%= link_to "Add Home", toggle_post_path(post.id), class: "small btn btn-success ", style: "font-size: 12px;margin: 8px;"  unless post.has_home? %>
            <%= link_to "Remove Home", toggle_post_path(post.id), class: "small btn btn-danger ", style: "font-size: 12px;margin: 8px;"   if post.has_home?%>
            <%= link_to "Delete", post_path(post.id), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "small btn btn-danger ", style: "font-size: 12px;margin-right: 8px;"%>
            
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="flex-row d-flex justify-content-between align-items-center p-4">
  <h3 class="fs-4">New Post</h3>
  <%= link_to "Back", posts_path, class: "btn btn-primary w-auto" %>
</div>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>