config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :audios
  resources :images
  # resources :post_contents
  resources :posts do
    resources :post_contents, controller: 'post_contents'

    member do
      get :toggle
    end
  end
  resources :labels
  resources :menus
  resources :local_names
  resources :country_names
  resources :countries
  resources :locals
  resources :languages
  devise_for :users
  namespace :api do
    resources :locals do
      collection do
        get :home 
      end
    end
    resources :languages
    resources :countries
    resources :labels
    resources :favorites
    resources :itineraries 
    resources :posts do
      collection do
        get :get_itineraries
        get :get_lat_lng
      end
    end

    post '/login' => 'sessions#signin'
    
    get '/auth' => 'users#get_user'
    post '/sign_up' => 'users#create'
    put '/users' => 'users#update_user'
    delete 'users/:id' => 'users#destroy'
    
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post_content.rb
class PostContent < ApplicationRecord
  belongs_to :post
  belongs_to :language

  validates :title, :content, presence: true
end

app/controllers/post_contents_controller.rb
class PostContentsController < ApplicationController
  before_action :set_post_content, only: %i[ show edit update destroy ]
  before_action :set_post

  # GET /post_contents or /post_contents.json
  def index
    @post_contents = PostContent.where(post_id: @post.id)
  end

  # GET /post_contents/1 or /post_contents/1.json
  def show
  end

  # GET /post_contents/new
  def new
    @post_content = PostContent.new
  end

  # GET /post_contents/1/edit
  def edit

    if params[:language_id].present?
      @post_content = @post.post_contents.where(language_id: params[:language_id]).last
    end
  end

  # POST /post_contents or /post_contents.json
  def create
    @post_content = PostContent.new(post_content_params)

    respond_to do |format|
      if @post_content.save
        format.html { redirect_to post_content_url(@post_content), notice: "Post content was successfully created." }
        format.json { render :show, status: :created, location: @post_content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_contents/1 or /post_contents/1.json
  def update
    respond_to do |format|
      if @post_content.update(post_content_params)
        format.html { redirect_to post_post_contents_url(@post), notice: "Post content was successfully updated." }
        format.json { render :show, status: :ok, location: @post_content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_contents/1 or /post_contents/1.json
  def destroy
    @post_content.destroy

    respond_to do |format|
      format.html { redirect_to post_contents_url, notice: "Post content was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_content
      @post_content = PostContent.find(params[:id])
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

    # Only allow a list of trusted parameters through.
    def post_content_params
      params.require(:post_content).permit(:title, :subtitle, :content, :post_id, :language_id)
    end
end

app/helpers/post_contents_helper.rb
module PostContentsHelper
end

app/views/post_contents/_form.html.erb
<div class="row m-3 ">
  <% Language.all.each do |language| %>
    <%= link_to language.name, edit_post_post_content_path(language_id: language.id), class: "btn #{@language.id === language.id ? "btn-primary" : "btn-primary-outline" } w-auto" %>
  <% end %>
</div>

<%= simple_form_for([@post, @post_content]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <h3>Content Post</h3>

    <%= f.input :title, input_html: { class: "form-control" } %>
    <%= f.input :subtitle, input_html: { class: "form-control" } %>
    <%#= f.input :content, as: :rich_text_area, input_html: { class: "form-control" }  %>
    <br />
    <%= f.cktext_area :content, id: 'sometext', cols: 400, input_html: {ckeditor: { toolbar: 'Full' }}  %>
    <br />
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/post_contents/_post_content.html.erb
<tr>
  <td><%= post_content&.post&.title %></td>
  <td><%= post_content.title %></td>
  <td><%= post_content.language&.name %></td>
  <td>
    <%= link_to "Edit", edit_post_post_content_path(@post, post_content, language_id: post_content.language_id), class: "btn btn-success" %>
  </td>
</tr>

app/views/post_contents/edit.html.erb
<%- model_class = PostContent -%>
<div class="flex-row d-flex justify-content-between align-items-center p-4">
  <h3 class="fs-4">Edit Post Content</h3>
  <%= link_to "Back", post_post_contents_path(@post), class: "btn btn-primary w-auto" %>
</div>

<%= render "form", post: @post %>

app/views/post_contents/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="row">
  <div class="col">
    <h1 class="mt-4">Post Content</h1>
    <div class="col d-flex justify-content-end align-items-center">
      <%= link_to "Back", posts_path, class: "btn btn-primary w-auto" %>
    </div>
  </div>
</div>
<div class="row">
  <table class="table">
    <thead>
        <tr>
            <th>Original title</th>
            <th>Title</th>
            <th>Language</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
      <% @post_contents.each do |post_content| %>
        <%= render post_content %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/post_contents/new.html.erb
<h1>New post content</h1>

<%= render "form", post_content: @post_content %>

<br>

<div>
  <%= link_to "Back to post contents", post_contents_path %>
</div>

app/views/post_contents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post_content %>

<div>
  <%= link_to "Edit this post content", edit_post_content_path(@post_content) %> |
  <%= link_to "Back to post contents", post_contents_path %>

  <%= button_to "Destroy this post content", @post_content, method: :delete %>
</div>