config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :audios
  resources :images
  # resources :post_contents
  resources :posts do
    resources :post_contents, controller: 'post_contents'

    member do
      get :toggle
    end
  end
  resources :labels
  resources :menus
  resources :local_names
  resources :country_names
  resources :countries
  resources :locals
  resources :languages
  devise_for :users
  namespace :api do
    resources :locals do
      collection do
        get :home 
      end
    end
    resources :languages
    resources :countries
    resources :labels
    resources :favorites
    resources :itineraries 
    resources :posts do
      collection do
        get :get_itineraries
        get :get_lat_lng
      end
    end

    post '/login' => 'sessions#signin'
    
    get '/auth' => 'users#get_user'
    post '/sign_up' => 'users#create'
    put '/users' => 'users#update_user'
    delete 'users/:id' => 'users#destroy'
    
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/local_name.rb
class LocalName < ApplicationRecord
  belongs_to :language
  belongs_to :local
end

app/controllers/local_names_controller.rb
class LocalNamesController < ApplicationController
  before_action :set_local_name, only: %i[ show edit update destroy ]

  # GET /local_names or /local_names.json
  def index
    @local_names = LocalName.all
  end

  # GET /local_names/1 or /local_names/1.json
  def show
  end

  # GET /local_names/new
  def new
    @local_name = LocalName.new
  end

  # GET /local_names/1/edit
  def edit
  end

  # POST /local_names or /local_names.json
  def create
    @local_name = LocalName.new(local_name_params)

    respond_to do |format|
      if @local_name.save
        format.html { redirect_to local_name_url(@local_name), notice: "Local name was successfully created." }
        format.json { render :show, status: :created, location: @local_name }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @local_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /local_names/1 or /local_names/1.json
  def update
    respond_to do |format|
      if @local_name.update(local_name_params)
        format.html { redirect_to local_name_url(@local_name), notice: "Local name was successfully updated." }
        format.json { render :show, status: :ok, location: @local_name }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @local_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /local_names/1 or /local_names/1.json
  def destroy
    @local_name.destroy

    respond_to do |format|
      format.html { redirect_to local_names_url, notice: "Local name was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local_name
      @local_name = LocalName.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def local_name_params
      params.require(:local_name).permit(:name, :language_id, :local_id)
    end
end

app/helpers/local_names_helper.rb
module LocalNamesHelper
end

app/views/local_names/_form.html.erb
<%= simple_form_for(@local_name) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :language %>
    <%= f.association :local %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/local_names/_local_name.html.erb
<div id="<%= dom_id local_name %>">
  <p>
    <strong>Name:</strong>
    <%= local_name.name %>
  </p>

  <p>
    <strong>Language:</strong>
    <%= local_name.language_id %>
  </p>

  <p>
    <strong>Local:</strong>
    <%= local_name.local_id %>
  </p>

</div>

app/views/local_names/edit.html.erb
<h1>Editing local name</h1>

<%= render "form", local_name: @local_name %>

<br>

<div>
  <%= link_to "Show this local name", @local_name %> |
  <%= link_to "Back to local names", local_names_path %>
</div>

app/views/local_names/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Local names</h1>

<div id="local_names">
  <% @local_names.each do |local_name| %>
    <%= render local_name %>
    <p>
      <%= link_to "Show this local name", local_name %>
    </p>
  <% end %>
</div>

<%= link_to "New local name", new_local_name_path %>

app/views/local_names/new.html.erb
<h1>New local name</h1>

<%= render "form", local_name: @local_name %>

<br>

<div>
  <%= link_to "Back to local names", local_names_path %>
</div>

app/views/local_names/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @local_name %>

<div>
  <%= link_to "Edit this local name", edit_local_name_path(@local_name) %> |
  <%= link_to "Back to local names", local_names_path %>

  <%= button_to "Destroy this local name", @local_name, method: :delete %>
</div>